services:
  app:
    container_name: app
    build:
      context: ..
      dockerfile: Dockerfile
      target: dev
    restart: always
    environment:
      ALLOW_ORIGINS: "http://localhost:3030,http://0.0.0.0:3030,http://0.0.0.0:8000"
      DB_MASTER_HOST: master_pg
    ports:
      - "8000:8000"
    env_file:
      - ../dev.env
    command:
      ["start", "8000"]
    depends_on:
      master_pg:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "true"]
      interval: 5s
      timeout: 3s
      retries: 5

  master_pg:
    container_name: db
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_PASSWORD=app_pswd
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  k6:
    image: grafana/k6:latest
    container_name: k6
    ports:
      - "5665:5665"
    volumes:
      - ./scripts:/scripts
      - ./k6_reports:/reports
    environment:
      - K6_WEB_DASHBOARD=true
      - K6_WEB_DASHBOARD_EXPORT=/reports/html-report.html

volumes:
  postgres_data:
