x-patroni-common: &patroni-common
  build:
    context: .
    dockerfile: ./patroni/Dockerfile.patroni
  networks:
    - infra
  environment:
    PATRONI_SCOPE: app_cluster
    PATRONI_NAME: ${PATRONI_NAME}
    PATRONI_POSTGRESQL_LISTEN: 0.0.0.0:5432
    PATRONI_POSTGRESQL_CONNECT_ADDRESS: ${PATRONI_NAME}:5432
    PATRONI_RESTAPI_LISTEN: 0.0.0.0:8008
    PATRONI_RESTAPI_CONNECT_ADDRESS: ${PATRONI_NAME}:8008
    PATRONI_ETCD_HOST: etcd:2379
    POSTGRES_PASSWORD: app_pswd
    POSTGRES_DB: app_db
  command: patroni /etc/patroni.yml
  depends_on:
    - etcd


services:
  app:
    container_name: app
    build:
      context: ..
      dockerfile: Dockerfile
      target: dev
    restart: always
    environment:
      ALLOW_ORIGINS: "http://localhost:3030,http://0.0.0.0:3030,http://0.0.0.0:8000"
      DB_MASTER_HOST: haproxy
    ports:
      - "8000:8000"
    env_file:
      - ../dev.env
    command:
      ["start", "8000"]
    depends_on:
      haproxy:
        condition: service_healthy
    networks:
      - infra

  patroni1:
    <<: *patroni-common
    container_name: patroni1
    environment:
      PATRONI_NAME: patroni1
    volumes:
      - ./patroni/patroni1.yaml:/etc/patroni.yml
      - pgdata1:/var/lib/postgresql:rw

  patroni2:
    <<: *patroni-common
    container_name: patroni2
    environment:
      PATRONI_NAME: patroni2
    volumes:
      - ./patroni/patroni2.yaml:/etc/patroni.yml:ro
      - pgdata2:/var/lib/postgresql:rw
    depends_on:
      patroni1:
        condition: service_started

  patroni3:
    <<: *patroni-common
    container_name: patroni3
    environment:
      PATRONI_NAME: patroni3
    volumes:
      - ./patroni/patroni3.yaml:/etc/patroni.yml:ro
      - pgdata3:/var/lib/postgresql:rw
    depends_on:
      patroni1:
        condition: service_started

  etcd:
    image: quay.io/coreos/etcd:v3.5.15
    hostname: etcd
    container_name: etcd
    networks:
      - infra
    environment:
      ETCD_NAME: etcd
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd:2380
      ETCD_INITIAL_CLUSTER: etcd=http://etcd:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: patroni
    healthcheck:
      test: ["CMD-SHELL", "etcdctl endpoint health --endpoints=http://localhost:2379"]
      interval: 10s
      timeout: 5s
      retries: 5

  haproxy:
    image: haproxy:2.9-alpine
    hostname: haproxy
    container_name: haproxy
    ports:
      - "5432:5432"
    networks:
      - infra
    volumes:
      - ./patroni/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    healthcheck:
      test: [ "CMD", "haproxy", "-c", "-f", "/usr/local/etc/haproxy/haproxy.cfg" ]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      patroni1:
        condition: service_started
      patroni2:
        condition: service_started
      patroni3:
        condition: service_started

  k6:
    image: grafana/k6:latest
    container_name: k6
    ports:
      - "5665:5665"
    volumes:
      - ./scripts:/scripts
      - ./k6_reports:/reports
    environment:
      - K6_WEB_DASHBOARD=true
      - K6_WEB_DASHBOARD_EXPORT=/reports/html-report.html

networks:
  infra:
    name: infra

volumes:
  pgdata1:
  pgdata2:
  pgdata3:
