ARG PG_VERSION=17
FROM postgres:${PG_VERSION}

ENV DEBIAN_FRONTEND=noninteractive

ARG PATRONI_DIR=/etc/patroni

USER root

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-dev \
    python3-setuptools \
    python3-wheel \
    gcc \
    build-essential \
    libpq-dev \
    curl \
    vim \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --break-system-packages patroni[etcd] psycopg

RUN mkdir -p /var/lib/postgresql/data ${PATRONI_DIR} \
    && chown -R postgres:postgres /var/lib/postgresql

USER postgres

CMD ["patroni", "/etc/patroni/patroni.yml"]