services:
  app:
    build:
      context: ..
      dockerfile: ../Dockerfile
      target: dev
    restart: always
    environment:
      ALLOW_ORIGINS: "http://localhost:3030,http://0.0.0.0:3030"
      DB_HOST: db
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - dev.env
    command:
      ["start", "8000"]
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_PASSWORD=app_pswd
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  k6:
    image: grafana/k6:latest
    container_name: k6
    volumes:
      - ./k6-scripts:/scripts
    depends_on:
      - app
      - prometheus
    entrypoint: ["k6", "run", "--out", "prometheus=http://prometheus:9090", "/scripts/script.js"]
